include:
  - project: gitlab-ci/kaniko-publish
    file: '.kaniko-build-push.gitlab-ci.yaml'
    ref: v0.x

variables:
  CI_REGISTRY_USER: sykeben

stages:
  - build
  - push
  - release

release-binaries:
  stage: push
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  when: manual
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
