streams:
  - name: Example Stream
    title: Example Stream
    description: "Example Description"
    schedule: "30 10 * * 0" # every sunday at 10:30
    delaySeconds: 1800 # delay for 30minutes
    privacyLevel: "unlisted"
    publish: true

publisher:
  wordpress:
    host: example.ca
    port: "443"
    tls: true
    username: "wp.admin"
    appToken: "ABCD EFGH IJKL MNOP"
    content: |
      <h1>{{ .Title }}</h1>
      <p>
      The stream is located at: {{ .Stream.URL }}
      </p>