streams:
  - name: Example Stream
    title: Example Stream
    description: "Example Description ... .. ... .."
    schedule: "*/1 * * * *" # every 10 minutes
    delaySeconds: 1800 # delay stream start time for 30 minutes
    privacy:
      level: "unlisted"
      # selfDeclaredMadeForKids: false
    # thumbnails:
    #   default:
    #     url: https://churchofgodhamilton.ca/wp-content/uploads/2023/04/pathway-g8cbc510b4_1920-min-min-min.jpg
    # publisher:
    #   wordpress:
    #     host: example.ca
    #     port: 80
    #     tls: no
    #     username: admin
    #     appToken: "AAAA BBBB CCCC DDDD EEEE FFFF"
    #     content:
    #       meta:
    #         status: published
    #       content: |
    #         <h1>Hello</h1>