oauthConfigPath: "/path/to/oauth_config.json"
streams:
  - name: Example Service
    titlePrefix: Example Service
    description: "Example Description"
    schedule: "30 10 * * 7" # every sunday at 10:30
    delaySeconds: 1800 # delay for 30minutes
    privacyLevel: "unlisted"

